# See https://github.com/containers/common/blob/master/pkg/config/containers.conf
[engine]
cgroup_manager = "cgroupfs"
conmon_path=["${XDG_DATA_HOME}/podman-dist/current/usr/local/lib/podman/conmon"]
events_logger="file"
helper_binaries_dir=["${XDG_DATA_HOME}/podman-dist/current/usr/local/bin", "${XDG_DATA_HOME}/podman-dist/current/usr/local/lib/podman"]
